// This file was generated by Prisma, and assumes you have installed the following:
// npm install --save-dev prisma dotenv
import "dotenv/config";
import { defineConfig } from "prisma/config";

export default defineConfig({
  schema: './prisma/schema.prisma',
  datasource: {
    url: process.env.DATABASE_URL, // Aquí es donde Prisma buscará la URL para hacer 'prisma migrate' o 'prisma format'
  },
  migrations: {
    seed: 'ts-node --transpile-only prisma/seed.ts', // 👈 Agrega esta sección aquí
  },
})


